### ISSUE TITLE
Transfer the ownership of `vue-cusdis` npm package

### ISSUE THREAD

**Issue by frostming** [evillt/vue-cusdis#3]
Tell me if you are Ok and I can continue

**Comment by 2nthony** [comment]
that's awesome. But how we do this?

**Comment by frostming** [comment]
I have invited you as the maintainer, you can try publishing to that package. After everything is Okay, I will quit when suitable

**Comment by 2nthony** [comment]
My npm id is: `evila`, different to github 😂

**Comment by frostming** [comment]
Already done, you can check your account.

**Comment by 2nthony** [comment]
Published.Thanks.
